name: Terraform environment deployment
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  terraform-test-deployment:
    uses: ./.github/workflows/tf-plan-approve-apply.yml
    with:
      environment: test
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
