name: TF DEPLOYMENT
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  tf-test-deployment:
    uses: ./.github/actions/tf-plan-approve-apply.yml@main
    with:
      environment: test
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
  start-prod-deployment:
    needs:
      - tf-test-deployment
    runs-on: ubuntu-latest
    environment: manual-step
    steps:
      - name: Manual Approve Info
        run: |
          terraform -v
          echo ${{ github.triggering_actor }}
          echo ${{ github.actor }}
  tf-prod-deployment:
    needs:
      - start-prod-deployment
    uses: ./.github/actions/tf-plan-approve-apply.yml@main
    with:
      environment: prod
      tf_dir: deployments
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}